# Generated by Django 5.0.1 on 2024-02-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffee_app', '0002_asociado_delete_resena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
