# Generated by Django 5.0.1 on 2024-02-15 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffee_app', '0006_alter_asociado_puesto_avatar_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='BebidaEnCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coffee_app.bebida')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coffee_app.carrito')),
            ],
        ),
        migrations.CreateModel(
            name='MerchEnCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coffee_app.carrito')),
                ('merch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coffee_app.merch')),
            ],
        ),
        migrations.CreateModel(
            name='PostreEnCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coffee_app.carrito')),
                ('postre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coffee_app.postre')),
            ],
        ),
    ]
