# Generated by Django 5.0.1 on 2024-02-25 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffee_app', '0007_bebidaencarrito_merchencarrito_postreencarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='calificacion',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
