# Generated by Django 5.0.1 on 2024-02-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffee_app', '0010_alter_bebida_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='imagen',
            new_name='foto',
        ),
        migrations.AlterField(
            model_name='bebida',
            name='descripcion',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='merch',
            name='descripcion',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='postre',
            name='descripcion',
            field=models.CharField(max_length=120),
        ),
    ]
